/*
 * Designed and developed by 2023 proeb (Emre BAHADIR)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.proeb.composethemer.processor.generator

import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec

/**
 * Created by emre bahadir on 9/24/2023
 */
internal class ComponentThemeFileGenerator(
    private val declaration: KSClassDeclaration
) {

    fun generate(): List<FileSpec> {
        val componentThemeFileSpec = arrayListOf<FileSpec>()
        val packageName = declaration.packageName.asString()
        val implClassFileName = "${declaration.simpleName.asString()}Impl"
        val defaultObjectFileName = "${declaration.simpleName.asString()}Defaults"
        val implClassName = ClassName.bestGuess("$packageName.$implClassFileName")
        val defaultObjectName = ClassName.bestGuess("$packageName.$defaultObjectFileName")

        val implClassSpec = ImplClassGenerator(
            declaration = declaration,
            className = implClassName
        ).generate()

        componentThemeFileSpec.add(
            FileSpec.builder(
                packageName,
                implClassFileName
            )
                .addFileComment("This class was generated by Compose Themer.\n")
                .addFileComment("Do not edit this file.")
                .addImport("androidx.compose.runtime", "rememberUpdatedState")
                .addType(implClassSpec)
                .build()
        )

        val defaultObjectSpec = DefaultObjectGenerator(
            declaration = declaration,
            className = defaultObjectName,
            implClassName = implClassName
        ).generate()

        componentThemeFileSpec.add(
            FileSpec.builder(
                packageName,
                defaultObjectFileName
            )
                .addFileComment("This class was generated by Compose Themer.\n")
                .addFileComment("Do not edit this file.")
                .addType(defaultObjectSpec)
                .build()
        )

        return componentThemeFileSpec
    }
}
